sortiramacon/events/urls.py
#!/usr/bin/env python
# encoding: utf-8
#
# Copyright (c) 2012 ASK interactive. All Rights Reserved.
#
# Created by AskinWeb <contact@askinweb.fr> on 2012-03-08.

"""Events module urls configuration"""

__author__ = 'AskinWeb <contact@askinweb.fr>'


from django.conf.urls.defaults import *

from events.models import Event

events_info_dict = {
    'queryset': Event.published.all(),
    'date_field': 'start_date',
}

events_info_month_dict = {
    'queryset': Event.published.all(),
    'date_field': 'start_date',
    'month_format': '%m',
    'allow_future': True
}

urlpatterns = patterns('django.views.generic.date_based',
    (r'^$', 'archive_index', events_info_dict, 'events_archive_index'),
    
    (r'^(?P<year>\d{4})/$',
     'archive_year', events_info_dict, 'events_archive_year'),
    
    #(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
    # 'archive_month', events_info_month_dict, 'event_archive_month'),
    
    (r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
     'archive_day', events_info_month_dict, 'events_archive_day'),
    
    #(r'^(?P<category>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
    # 'object_detail', news_info_month_dict, 'news_detail'),
)

urlpatterns += patterns('events.views',
    # By category --------
    
    url(
        r'^(?P<category>[-\w]+)/$', 
        'archive_category_index', 
        name='event_archive_category_index'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/$',
        'archive_category_year', 
        name='event_archive_category_year'
    ),
    
    url(
        r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        'archive_month', 
        name='event_archive_month'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/$',
        'archive_category_month', 
        name='event_archive_category_month'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        'archive_category_day', 
        name='event_archive_category_day'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        'object_detail', 
        name='event_detail'
    ),
)

sortiramacon/news/urls.py
from django.conf.urls.defaults import *

from news.models import News

news_info_dict = {
    'queryset': News.published.all(),
    'date_field': 'pub_date',
}

news_info_month_dict = {
    'queryset': News.published.all(),
    'date_field': 'pub_date',
    'month_format': '%m',
}

urlpatterns = patterns('django.views.generic.date_based',
    (r'^$', 'archive_index', news_info_dict, 'news_archive_index'),
    
    (r'^(?P<year>\d{4})/$',
     'archive_year', news_info_dict, 'news_archive_year'),
    
    (r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
     'archive_month', news_info_month_dict, 'news_archive_month'),
    
    (r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
     'archive_day', news_info_month_dict, 'news_archive_day'),
)

urlpatterns += patterns('news.views',
    # By category --------
    
    url(
        r'^(?P<category>[-\w]+)/$', 
        'archive_category_index', 
        name='news_archive_category_index'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/$',
        'archive_category_year', 
        name='news_archive_category_year'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/$',
        'archive_category_month', 
        name='news_archive_category_month'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        'archive_category_day', 
        name='news_archive_category_day'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        'object_detail', 
        name='news_detail'
    ),
)

sortiramacon/restaurants/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('restaurants.views',
    # By category --------
    
    url(
        r'^$', 
        'archive_index', 
        name='restaurant_archive_index'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/$', 
        'archive_category_index', 
        name='restaurant_archive_category_index'
    ),
    
    url(
        r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        'object_detail', 
        name='restaurant_detail'
    ),
)

sortiramacon/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.conf import settings
from sortiramacon.news.sitemaps import NewsSitemap
from sortiramacon.events.sitemaps import EventsSitemap
from sortiramacon.movies.sitemaps import MoviesSitemap
from sortiramacon.restaurants.sitemaps import RestaurantsSitemap
from sortiramacon.associations.sitemaps import AssociationsSitemap

from cms.sitemaps import CMSSitemap

sitemaps = {
    'news': NewsSitemap, 
    'events': EventsSitemap,
    'movies': MoviesSitemap,
    'restaurants': RestaurantsSitemap,
    'associations': AssociationsSitemap,
    'pages': CMSSitemap
}



urlpatterns = patterns('',
    url(r'^actualites/', include('sortiramacon.news.urls')),
    url(r'^evenements/', include('sortiramacon.events.urls')),
    url(r'^lieux/', include('sortiramacon.events.place_urls')),
    
    url(r'^restaurants/', include('sortiramacon.restaurants.urls')),
    url(r'^associations/', include('sortiramacon.associations.urls')),

    url(r'^films/', include('sortiramacon.movies.urls')),

    
    (r'^rechercher/', include('haystack.urls')),
    

    
    (r'^sitemap-(?P<section>.+)\.xml$', 'sortiramacon.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    url(r'^sitemap-pages.xml$', 'sortiramacon.sitemaps.views.sitemap', {'sitemaps': {'pages': CMSSitemap}}),

    url(r'^sitemap.xml$', 'sortiramacon.sitemaps.views.index',  {'sitemaps': sitemaps}),

    url(r'^', include('zebnetcms.urls')),

)

if settings.DEBUG:
    urlpatterns = patterns('',
        (r'^' + settings.MEDIA_URL.lstrip('/'), include('appmedia.urls')),
    ) + urlpatterns

sortiramacon/associations/models.py
# -*- coding: utf-8 -*-

import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _

from django.conf import settings

from cms.models import CMSPlugin


class AssociationCategory(models.Model):
    """
    Category
    """
    
    title           = models.CharField(_('Title'), max_length=255)
    
    slug            = models.SlugField(_('Slug'))
    
    content         = models.TextField(_('content'), blank=True)
    
    order           = models.IntegerField(_('order'), default=20)
    
    created         = models.DateTimeField(auto_now_add=True, editable=False)
    updated         = models.DateTimeField(auto_now=True, editable=False)
    
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ('order', )
    
    
    def __unicode__(self):
        try:
            return u'%s'% (self.title)
        except:
            return u'Auncun titre'
    
    @models.permalink
    def get_absolute_url(self):
        return ('association_archive_category_index', (), {
            'category': self.slug,
            })


class PublishedAssociationsManager(models.Manager):
    """ Filters out all unpublished and items with a publication date in the future. """
    
    def get_query_set(self):
        return super(PublishedAssociationsManager, self).get_query_set().filter(is_published=True)


class Association(models.Model):
    """ Association model """
    
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), unique=True, 
                            help_text=_('A slug is a short name which uniquely identifies the news item for this day'))
    
    
    phone   = models.CharField(_('phone'), blank=True, max_length=80)
    address = models.TextField(_('address'), blank=True)
    website = models.CharField(_('website'), blank=True, max_length=250)
    email   = models.CharField(_('email'), blank=True, max_length=80)
    
    content = models.TextField(_('Content'), blank=True)
    
    image  = models.ImageField(_('Image'), upload_to="associations/", null=True, blank=True)
    
    category = models.ForeignKey(AssociationCategory, related_name="a_category", verbose_name=_("Category"))
    
    is_published = models.BooleanField(_('Published'), default=False)
    
    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)
    
    published = PublishedAssociationsManager()
    objects   = models.Manager()
    
    
    class Meta:
        verbose_name = _('Association')
        verbose_name_plural = _('Associations')
        ordering = ('title', )
    
    
    def __unicode__(self):
        try:
            return u'%s'% (self.title)
        except:
            return u'Auncun titre'
    
    @models.permalink
    def get_absolute_url(self):
        return ('association_detail', (), {
            'category': self.category.slug,
            'slug': self.slug,
            })


class LatestAssociationsPlugin(CMSPlugin):
    """ Model for the settings when using the latest news cms plugin. """
    
    category = models.ForeignKey(AssociationCategory, null=True, blank=True, default=None)
    
    limit    = models.PositiveIntegerField(_('Number of items to show'), 
               help_text=_('Limits the number of items that will be displayed'))


class AssociationPhoto(models.Model):
    """
    Photo for association
    """
    
    title           = models.CharField(_('Title'), max_length=255)
    
    image           = models.ImageField(_('Image'), upload_to="associations/photos/",)
    
    order           = models.IntegerField(_('order'), default=20)
    
    restaurant      = models.ForeignKey(Association, verbose_name=_('association'))
    
    created         = models.DateTimeField(auto_now_add=True, editable=False)
    updated         = models.DateTimeField(auto_now=True, editable=False)
    
    
    class Meta:
        verbose_name = _('Photo')
        verbose_name_plural = _('Potos')
        ordering = ('order', 'created')
    
    
    def __unicode__(self):
        try:
            return u'%s'% (self.title)
        except:
            return u'Auncun titre'

sortiramacon/associations/forms.py
from django import forms
from django.conf import settings

from cms.plugin_pool import plugin_pool
from cms.plugins.text.settings import USE_TINYMCE
from cms.plugins.text.widgets.wymeditor_widget import WYMEditor

from associations.models import Association, AssociationCategory

class AssociationForm(forms.ModelForm):
    class Meta:
        model = Association
        
    def _get_widget(self):
        plugins = plugin_pool.get_text_enabled_plugins(placeholder=None, page=None)
        if USE_TINYMCE and "tinymce" in settings.INSTALLED_APPS:
            from news.widgets.tinymce_widget import TinyMCEEditor
            return TinyMCEEditor(installed_plugins=plugins)
        else:
            return WYMEditor(installed_plugins=plugins)
        
        
    def __init__(self, *args, **kwargs):
        super(AssociationForm, self).__init__(*args, **kwargs)
        widget = self._get_widget()
        self.fields['content'].widget = widget


class AssociationCategoryForm(forms.ModelForm):
    class Meta:
        model = AssociationCategory
        
    def _get_widget(self):
        plugins = plugin_pool.get_text_enabled_plugins(placeholder=None, page=None)
        if USE_TINYMCE and "tinymce" in settings.INSTALLED_APPS:
            from news.widgets.tinymce_widget import TinyMCEEditor
            return TinyMCEEditor(installed_plugins=plugins)
        else:
            return WYMEditor(installed_plugins=plugins)
        
        
    def __init__(self, *args, **kwargs):
        super(AssociationCategoryForm, self).__init__(*args, **kwargs)
        widget = self._get_widget()
        self.fields['content'].widget = widget

sortiramacon/associations/views.py
# Create your views here.
from django.http import Http404

from django.views.generic import list_detail

from associations.models import Association
from associations.models import AssociationCategory

def archive_index(request):
    
    queryset = AssociationCategory.objects.all()
    
    
    return list_detail.object_list(
                        request,
                        queryset,
                        paginate_by=50)


def archive_category_index(request, category):
    cat = AssociationCategory.objects.get(slug=category)
    
    queryset = Association.published.filter(category=cat)
    
    
    return list_detail.object_list(
                        request,
                        queryset,
                        paginate_by=15)

def object_detail(request, category, slug):
    queryset = Association.published.all()
    
    return list_detail.object_detail(
                        request,
                        queryset,
                        slug=slug)

sortiramacon/templates/associations/association_detail.html
{% extends "associations/base_association.html" %}

{% load i18n thumbnail %}

{% block page_title %}{{ object.title }}{% endblock %}

{% block content_news %}


<div id="post-header">
    <div class="post-title clear">
        <div class="header-title">
            <h1>{{ object.title }}</h1>
        </div>
    </div>
</div>

<div class="published">
    <p><a href="{{ object.category.get_absolute_url }}">{{ object.category }}</a></p>
</div>

<div class="post-columns clear">
    <div class="post type-post status-publish format-standard hentry category-movies category-videos tag-action-movie tag-captain-america tag-comic-book-movie tag-movie-trailers tag-the-avengers post-460 post-entry">
        {% if object.image %}
        <div class="wp-caption alignright" style="width: 310px">
            <a title="{{ object.title }}" href="{{ object.image.url}}" rel="fancybox-gallery">
                {% thumbnail object.image "300x220" crop="center" as im %}<img title="{{ object.title }}" alt="{{ object.title }}" class="size-medium" src="{{ im.url }}">{% endthumbnail %}
            </a>
        </div>
        {% endif %}
        <blockquote class="pullquote pullright alignleft" style="margin-bottom:20px">
            <h4>{{ object.title }}</h4>
            <p>
                <strong><a href="{{ object.category.get_absolute_url }}">{{ object.category }}</a></strong><br />
                {% if object.address %}<a href="http://maps.google.fr/maps?q={{ object.address|urlencode }},+France" target="_blank">{{ object.address|linebreaksbr }}</a><br/><a href="http://maps.google.fr/maps?q={{ object.address|urlencode }},+France" target="_blank"><strong>Voir sur Google Maps ›</strong></a><br/><br/>{% endif %}
                {% if object.phone %}<strong>Tél. : </strong>{{ object.phone }}<br/>{% endif %}
                {% if object.website %}<strong>Site web. : </strong><a href="http://{{ object.website }}" target="_blank">{{ object.website }}</a><br/>{% endif %}
                {% if object.email %}<strong>Email. : </strong><a href="mailto:{{ object.email }}">{{ object.email }}</a><br/>{% endif %}
            </p>
        </blockquote>
        <div class="clear"></div>
        
        {{ object.content|safe }}
    
        <div class="clear"></div>
        {% if object.associationphoto_set.all|length > 0 %}
        
        <h3>Les photos de l'association : {{ object.title }}</h3>
        
        <div class="gallery gallery-columns-3 gallery-size-thumbnail" id="gallery-1">
            {% for p in object.associationphoto_set.all %}
            <dl class="gallery-item">
                <dt class="gallery-icon">
                    <a title="{{ p.title }}" href="{{ p.image.url }}" rel="fancybox-gallery">{% thumbnail p.image "150x150" crop="center" as im %}<img title="{{ p.title }}" alt="{{ p.title }}" class="attachment-thumbnail" src="{{ im.url }}">{% endthumbnail %}</a>
                </dt>
            </dl>
            {% endfor %}
            <br style="clear: both;">
        </div>
        {% endif %}
        
    </div>
    <div class="clear"></div>
</div>

{% endblock %}

sortiramacon/templates/associations/association_list.html
{% extends "associations/base_association.html" %}

{% load i18n thumbnail %}

{% block page_title %}Les associations "{{ object_list.0.category }}" à Mâcon{% endblock %}

{% block content_news %}
<div id="page-title">
    <h1>Les associations "{{ object_list.0.category }}" à Mâcon</h1>
</div>

<div id="archived-posts">
    <ul class="clear">
        {% for object in object_list %}
        <li class="liasso">
            <div class="post type-post format-standard rel-post">
                <div class="sidebar-archive-thumb">
                    <p>
                        <a href="{{ object.get_absolute_url }}" rel="bookmark" title="{{ object.title }}">
                            {% thumbnail object.image "60x60" crop="center" as im %}<img src="{{ im.url }}" class="attachment-thumbnail-sidebar wp-post-image" alt="{{ object.title }}" title="{{ object.title }}" />{% endthumbnail %}
                        </a>
                    </p>
                </div>
                <div class="rel-post-text">
                    <h2>
                        <a href="{{ object.get_absolute_url }}" rel="bookmark" title="{{ object.title }}" style="font-size:12px;font-weight:bold;text-decoration:none;color:#222">{{ object.title }}</a>
                    </h2>
                    <p class="meta-data">
                        {{ object.address|linebreaksbr }}
                    </p>
                    {% if object.phone %}
                    <p class="alignleft"><strong>Tél. :</strong> {{ object.phone }}</p>
                    {% endif %}
                    <p class="alignright"><a href="{{ object.get_absolute_url }}">Voir la fiche »</a>
                    </p>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

{% if is_paginated %}
<div class="pagination">
    <div class="wp-pagenavi">
        <span class="pages">Page {{ page_obj.number }} sur {{ paginator.num_pages }}</span>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="previouspostslink">« Précédent</a>
        {% endif %}
        <span class="current">{{ page_obj.number }}</span>
        {#<a href="" class="page larger">{{ paginator.page_range }}</a>#}
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="nextpostslink">Suivant »</a>
        {% endif %}
    </div>
</div>
{% else %}
<div><br/></div>
{% endif %}

{% endblock %}

sortiramacon/templates/associations/associationcategory_list.html
{% extends "associations/base_association.html" %}

{% load i18n thumbnail %}

{% block page_title %}Les associations de Mâcon : clubs de sport, ecole de musique, garde d'enfants à Mâcon{% endblock %}

{% block content_news %}
<div id="page-title">
    <h1>Les associations à Mâcon</h1>
</div>

<div id="archived-posts">
    <ul class="clear">
        {% for object in object_list %}
        <li>
            <div class="post type-post format-standard rel-post">
                <div class="rel-post-text" style="float:none;width:100%">
                    <h2>
                        <a href="{{ object.get_absolute_url }}" rel="bookmark" title="{{ object.title }}" style="font-size:12px;font-weight:bold;text-decoration:none;color:#222">{{ object.title }}</a>
                    </h2>
                    <p class="meta-data">
                        {{ object.content|safe }}
                    </p>
                    <p class="alignright"><a href="{{ object.get_absolute_url }}">Voir toutes les associations "{{ object.title }}" »</a>
                    </p>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

{% if is_paginated %}
<div class="pagination">
    <div class="wp-pagenavi">
        <span class="pages">Page {{ page_obj.number }} sur {{ paginator.num_pages }}</span>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="previouspostslink">« Précédent</a>
        {% endif %}
        <span class="current">{{ page_obj.number }}</span>
        {#<a href="" class="page larger">{{ paginator.page_range }}</a>#}
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="nextpostslink">Suivant »</a>
        {% endif %}
    </div>
</div>
{% else %}
<div><br/></div>
{% endif %}

{% endblock %}

sortiramacon/templates/associations/base_association.html
{% extends "right-column.html" %}

{% block page_title %}{% endblock %}

{% block left_column %}
    {% block content_news %}{% endblock %}
{% endblock %}